apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: questsync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:SDR3078/questsync.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: questsync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
